export enum transitionsEnum {
  FADE_IN = "FADE IN",
  FADE_OUT = "FADE OUT",
  FADE_UP = "FADE UP",
  JUMP_CUT = "JUMP CUT",
  MATCH_CUT = "MATCH CUT",
  SMASH_CUT = "SMASH MATCH CUT",
  MATCH_DISSOLVE = "MATCH DISSOLVE",
  CUT = "CUT",
  DISSOLVE = "DISSOLVE",
  FLASH_CUT = "FLASH CUT",
  FREEZE_FRAME = "FREEZE FRAME",
  IRIS_IN = "IRIS IN",
  IRIS_OUT = "IRIS OUT",
  WIPE = "WIPE TO"
}
